import type { Metadata } from "next";
// Google Fontsをインポート
import { Roboto_Mono, Source_Code_Pro } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

// フォント設定
const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono", // CSS変数として定義
});
const sourceCodePro = Source_Code_Pro({
  subsets: ["latin"],
  variable: "--font-source-code-pro", // CSS変数として定義
});

export const metadata: Metadata = {
  title: "Your Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${robotoMono.variable} ${sourceCodePro.variable}`}>
        <Header /> {/* Headerコンポーネントをここに追加 */}
        <main className="pt-20"> {/* ヘッダーの高さ分だけpaddingを追加 */}
          {children}
        </main>
      </body>
    </html>
  );
}
